last_build_profile = "adl_middleware=RELEASE,cortex_m=RELEASE,embedded_components=RELEASE,gnat_arm_elf=RELEASE,hal=RELEASE,hw_refactor=DEVELOPMENT,stm32_hal=RELEASE,stm32f429disco=RELEASE"
[toolchain]
assistant = false
[toolchain.external]
gnat = false
[toolchain.use]
gnat = "gnat_arm_elf=12.2.1"

