name = "host_serial"
description = ""
version = "0.1.0-dev"

authors = ["RLT"]
maintainers = ["RLT <example@example.com>"]
maintainers-logins = ["github-username"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []
